services:
  - type: web
    name: esteri-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 24h
      - key: FRONTEND_URL
        value: https://esterimbenim.netlify.app
    healthCheckPath: /api/health
    autoDeploy: true