services:
  - type: web
    name: esteri-backend
    env: node
    region: frankfurt
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    numInstances: 1
    plan: free
    disk:
      name: esteri-uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1