services:
  - type: web
    name: esteri-backend
    env: node
    region: frankfurt
    buildCommand: |
      cd backend
      npm install
      npm run build
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: FRONTEND_URL
        value: https://esterimbenim.netlify.app
    healthCheckPath: /api/health
    healthCheckTimeout: 300
    autoDeploy: true
    numInstances: 1
    plan: free
    disk:
      name: esteri-uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 90
      targetCPUPercent: 90